### PR TITLE
ADD: wbs code and estimated start date to CW ticket class

### PR DESCRIPTION
**Pull request by kti-daniel**

### CODE REVIEW

**Comment by kti-cameron** [comment]
Only problem I'm seeing is 2 test fails when running `make test`:

```
======================================================================                         
FAIL: test_sync_skips (djconnectwise.tests.test_sync.TestProjectTicketSynchronizer)            
----------------------------------------------------------------------                         
Traceback (most recent call last):                                                             
  File "/home/cameron/Dev/Kanban/django-connectwise/djconnectwise/tests/test_sync.py", line 1494
, in test_sync_skips                                                                           
    self.assertEqual(skipped_count, len(fixture_list))                                         
AssertionError: 0 != 1                                                                         
                                                                                               
======================================================================                         
FAIL: test_sync_skips (djconnectwise.tests.test_sync.TestServiceTicketSynchronizer)            
----------------------------------------------------------------------                         
Traceback (most recent call last):                                                             
  File "/home/cameron/Dev/Kanban/django-connectwise/djconnectwise/tests/test_sync.py", line 1494
, in test_sync_skips                                                                           
    self.assertEqual(skipped_count, len(fixture_list))                                         
AssertionError: 0 != 1                                                                                                                                                                     
```
Are you seeing them in your env?

**Comment by kti-daniel** [comment]
Good point. I've found the same problem in master branch, too. I will handle that issue in this ticket.

**Comment by kti-daniel** [comment]
The above is fixed. Now you can have another look. (& master branch is okay. I think I was confused yesterday.)

**Comment by kti-cameron** [comment]
Looks good. Thanks

**Pull request merged**
