### PR TITLE
Added post request for creating time entry

### PR DESCRIPTION
**Pull request by kti-sam**

### CODE REVIEW

**Comment by kti-sam** [comment]
Realized we can just trust the person calling the method to call it with whatever they want, making it future proof for the most part. Now if CW changes any of the details we don't have to update django-connectwise, just whatever uses django-connectwise.

**Comment by kti-matt** [comment]
That cuts both ways though... if CW changes something, then you might HAVE to change whatever uses django-connectwise, not just django-connectwise itself.

One of the main benefits of a library is that the library can be responsible for insulating the user from changes to whatever lives behind the library.

Also, `post_time_entry` offers no clue whatsoever how to use it; compare with `post_schedule_entry` whose content gives clues how to use it. One would need to look up the CW developer docs to understand what to do with `post_time_entry`, which shouldn't be necessary when using a library.

I think there's sufficient reason to make a real implementation of `post_time_entry`.

**Comment by kti-sam** [comment]
See, I did that originally and second guessed myself. At least this was as easy as hitting ctrl+z

**Comment by kti-sam** [comment]
Oh wait, forgot I never fixed the pep8 violations before I deleted all of it, one moment

**Comment by kti-sam** [comment]
Ok, ready for review

**Comment by kti-matt** [comment]
Are you sure `+=` works for dictionaries?

```>>> d = {'a': 1}
>>> d += {'b': 2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'
```
says it doesn't.

`dict.update` is how I've done this before.

**Comment by kti-sam** [comment]
Wow

**Comment by kti-matt** [comment]
Does setting the member work? This doesn't match either `post_schedule_entry` or the CW developer docs, both of which set `member` as a dict with `id` and `identifier` fields.

**Comment by kti-sam** [comment]
I am so sorry, I am rushing and apparently my brain is just checked out this afternoon.

**Comment by kti-matt** [comment]
This should do more for the user. I don't think the user should need to know that `chargeToId` and `chargeToType` need to be set, and how to set them. It should take a `ticket` argument, or maybe `target` (or similar) if we want to be ready to take activities in the future, and then figure out what needs to be done in the request.

What's the format of the time fields? It looks like it needs to be provided as a string that the CW API accepts- but it should accept `datetime`'s. (`datetime.isoformat` should be helpful.)

Please make it accept arguments in Pythonic `lowercase_with_underscores` style, not `camelCase` style that the API expects.

Thanks!

**Pull request merged**
