### PR TITLE
sync work type and role for ticket

### PR DESCRIPTION
**Pull request by kti-sam**

### CODE REVIEW

**Comment by kti-matt** [comment]
I believe this still needs a synchronizer updated to set the new fields.

**Comment by kti-sam** [comment]
Ugh, must have missed committing or something. Because I tested it and it worked, and it wouldn't have worked without that haha

**Comment by kti-sam** [comment]
Pushed, cant test myself right now though, in class

**Comment by kti-matt** [comment]
Thanks. It syncs now.

What's the reasoning for making the 2 new fields `blank=False` when almost all the fields on Ticket are `blank=True`?

**Comment by kti-sam** [comment]
Its been so long since I've had to add fields, I probably just forgot I needed to specify blank=False as well as null. Fixing shortly.

**Comment by kti-sam** [comment]
Fixed!

**Pull request merged**
